---
title: "Modeling"
author: "Megan Glass"
date: "2023-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Libraries
```{r}
library(nflfastR)
library(cfbfastR)
library(ggplot2)
library(dplyr)


library(tidyverse) 
library(ggdark)
library(ggimage)
library(GGally)
library(ggrepel)


#install.packages("remotes")
#remotes::install_github("robkravec/ggfootball")
library(ggfootball)

library(caret)
library(pROC)
```

# Load Data

```{r}
tackle.data <- data.table::fread("tackle_events/all_week_tackle_data.csv")
plays_dat <- data.table::fread("plays.csv")
```

# Add Offense Formation, Defenders in the Box, Position Group

```{r}
add_data <- plays_dat %>%
  select(gameId, playId, offenseFormation, defendersInTheBox)
tackle.data <- merge(tackle.data, add_data, by = c('gameId', 'playId'))

tackle.data <- tackle.data %>%
  group_by(position) %>%
  mutate(group = ifelse(position == "DE" | position == "DT" | position == "NT", "lineman",
                        ifelse(position == "ILB" | position == "MLB" | position == "OLB", "linebacker", 
                               ifelse (position == "SS" | position == "FS", "safety", "cornerback"))))
```


# Logistic Regression of tackle data

```{r}
reg.tackle.data <- tackle.data[, c(4,13:20, 22:24,27:35,40:41)]

#training and validation datasets - 70% training/ 30% validation
set.seed(123)
train.rows <- sample(1:dim(reg.tackle.data)[1], dim(reg.tackle.data)[1]*0.7) 
train.df<-reg.tackle.data[train.rows,]
valid.df <- reg.tackle.data[-train.rows,]

#logistic reg model for all predictors
tackle.reg <- glm(tackle ~., data = train.df, family = "binomial") 
options(scipen=999)
summary(tackle.reg)
```


## Prediction

```{r}
# use predict() with type = "response" to compute predicted probabilities. 
tackle.reg.pred <- predict(tackle.reg, valid.df, type = "response")

#assigning predicted class = 1 for predicted probability > cutoff and 0 otherwise (cutoff = 0.5)
cutoff <- 0.5
pred_class <- ifelse(tackle.reg.pred> cutoff, 1, 0)
confusionMatrix(as.factor(pred_class), as.factor(valid.df$tackle), positive = "1")
```


## AUC and threshold

```{r}
roc <- roc(valid.df$tackle, tackle.reg.pred)
plot(roc)
auc(roc)
coords(roc, "best", ret = 
        "threshold", transpose = TRUE) # find the best cutoff

cutoff2 <-  0.8332373  
pred_class <- ifelse(tackle.reg.pred> cutoff2, 1, 0)
confusionMatrix(as.factor(pred_class), as.factor(valid.df$tackle), positive = "1")
```

## Add predictions

```{r}
tackle.data$prediction <- predict(tackle.reg, tackle.data, type = "response")
```

## Add adjusted x and y values for plotting
```{r}
# Adjust the x and y values, then rerun on 

tackle.data <- tackle.data %>%
  mutate(adjusted_x = 60 + x_dist_football,
         adjusted_y = 26.5 + y_dist_football)

tackle.data$adjusted_x <- ifelse(tackle.data$adjusted_x < 60, 
                                        60 + (60-tackle.data$adjusted_x),
                                        tackle.data$adjusted_x)
```

# Analyze Kansas City Chiefs Tackle Probabilities

```{r}
tackle.data %>%
  filter(club == "KC") %>%
  group_by(offenseFormation) %>%
  summarise(tackle.prob = mean(prediction)) %>%
  arrange(desc(tackle.prob))


SHOTGUN.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "SHOTGUN") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

SHOTGUN.tackle.dat %>% group_by(displayName) %>% summarise(avg.prob = mean(tackle.prob)) %>% arrange(desc(avg.prob))

EMPTY.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "EMPTY") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

EMPTY.tackle.dat %>% group_by(displayName) %>% summarise(avg.prob = mean(tackle.prob)) %>% arrange(desc(avg.prob))

IFORM.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "I_FORM") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

IFORM.tackle.dat  %>% group_by(displayName) %>% summarise(avg.prob = mean(tackle.prob)) %>% arrange(desc(avg.prob))

SINGLEBACK.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "SINGLEBACK") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

SINGLEBACK.tackle.dat

PISTOL.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "PISTOL") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

PISTOL.tackle.dat

JUMBO.tackle.dat <- tackle.data %>%
  filter(club == "KC", offenseFormation == "JUMBO") %>%
  group_by(displayName) %>%
  mutate(tackle.prob = mean(prediction), 
            avg.dist.snap = mean(football_dist_snap)) %>%
  arrange(desc(tackle.prob))

JUMBO.tackle.dat


```




```{r}
g_1 <- ggfootball() + geom_point(data = SHOTGUN.tackle.dat,
    aes(x = adjusted_x, y = adjusted_y, col = prediction, size = 1.5, alpha = 0.6)) +
   geom_vline(xintercept =60, lty=2,col="red", size=2) +
   guides(size = "none", alpha = "none")+
   theme(panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank(),
    aspect.ratio = 9 / 16,
    plot.title = element_text(size = 12, hjust = 0.5, face = "bold")) +  # Remove grid
    labs(title = "Tackle Probability Against Shotgun Formation")
  
  
g_1


g_2 <- ggfootball() + geom_point(data = IFORM.tackle.dat,
    aes(x = adjusted_x, y = adjusted_y, color = prediction, size = 3)) +
   geom_vline(xintercept =60, lty=2,col="red", size=2)+
  guides(size = "none")+
   theme(panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank(),
    aspect.ratio = 9 / 16,
    plot.title = element_text(size = 12, hjust = 0.5, face = "bold")) +  # Remove grid
    labs(title = "Tackle Probability Against I-Formation")
  
  
g_2

g_3 <- ggfootball() + 
  geom_point(data = EMPTY.tackle.dat,
    aes(x = adjusted_x, y = adjusted_y, col = prediction, size = 3)) +
   geom_vline(xintercept =60, lty=2,col="red", size=2)+
  guides(size = "none")+
   theme(panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank(),
    aspect.ratio = 9 / 16,
    plot.title = element_text(size = 12, hjust = 0.5, face = "bold")) +  # Remove grid
    labs(title = "Tackle Probability Against Empty Formation")

  
g_3
```





